import pygame

NEXT=pygame.USEREVENT+1
PLANT_PLANTED=pygame.USEREVENT+2
SHOVEL_BACK=pygame.USEREVENT+3
SEED_PACKET_0=pygame.USEREVENT+4
SEED_PACKET_1=pygame.USEREVENT+5
SEED_PACKET_2=pygame.USEREVENT+6
SEED_PACKET_3=pygame.USEREVENT+7
SEED_PACKET_4=pygame.USEREVENT+8
SEED_PACKET_5=pygame.USEREVENT+9
SEED_PACKET_6=pygame.USEREVENT+10
SEED_PACKET_7=pygame.USEREVENT+11
SEED_PACKET_8=pygame.USEREVENT+12
SEED_PACKET_9=pygame.USEREVENT+13

SEED_PACKET = [SEED_PACKET_0, SEED_PACKET_1, SEED_PACKET_2, SEED_PACKET_3, SEED_PACKET_4, SEED_PACKET_5, SEED_PACKET_6,SEED_PACKET_7,SEED_PACKET_8,SEED_PACKET_9]